query GetAnimeList($page: Int, $perPage: Int) {
  Page(page: $page, perPage: $perPage) {
    media {
      id
      coverImage {
        medium
      }
      genres

      title {
        english
      }
    }
  }
}
